### ISSUE TITLE
Use of Service account failing with traceback.

### ISSUE THREAD

**Issue by daniejstriata** [jay0lee/got-your-back#44]
Running a backup using a service account fails as can be seen below. (This worked fine on versions older than 0.29.)
This from 0.31 on Python 2.7.10.

"/usr/bin/python2.7 gyb.py --email username@domain.com --action backup --service-account serviceaccount@developer.gserviceaccount.com"

Traceback (most recent call last):
  File "gyb.py", line 1333, in <module>
    main(sys.argv[1:])
  File "gyb.py", line 578, in main
    imapconn = gimaplib.ImapConnect(generateXOAuthString(options.email, options.service_account), options.debug)
  File "gyb.py", line 268, in generateXOAuthString
    credentials = oauth2client.client.SignedJwtAssertionCredentials(service_account_name=service_account_name, private_key=key, scope=scope, user_agent=getGYBVersion(' / '), prn=email)
AttributeError: 'module' object has no attribute 'SignedJwtAssertionCredentials'

**Comment by volopasse** [comment]
I have the same issue, running v.0.31 and either python3 (v.3.2.3) or python2 (v.2.7.3)

**Comment by jay0lee** [comment]
IMAP versions are no longer supported, please upgrade to latest release.
